apiVersion: v1
kind: Pod
metadata:
  name: echo-health
  labels:
    app: echo
spec:
  containers:
  - name: app
    image: ghcr.io/subicura/echo:v1
    livenessProbe:
      httpGet:
        path: /
        port: 3000
    readinessProbe:
      httpGet:
        path: /
        port: 3000

# livenessProbe + readinessProbe
# 보통 livenessProbe와 readinessProbe를 같이 적용합니다. 상세한 설정은 애플리케이션 환경에 따라 적절하게 조정합니다.
# 3000번 포트와 / 경로는 정상적이기 때문에 Pod이 오류없이 생성된 것을 확인할 수 있습니다.
