apiVersion: v1
kind: Pod
metadata:
  name: alpine-env
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep"]
      args: ["100000"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username.txt
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password.txt
# # secret 생성
# kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt

# # secret 상세 조회
# kubectl describe secret/db-user-pass

# # -o yaml로 상세 조회
# kubectl get secret/db-user-pass -o yaml

# # 저장된 데이터 base64 decode
# echo 'MXEydzNlNHI=' | base64 --decode
# kubectl apply -f alpine-env.yml

# # env 확인
# kubectl exec -it alpine-env -- env
